### PR TITLE
Integrate with CircleCI

### PR DESCRIPTION
**Pull request by Git-Jiro**

### CODE REVIEW

**Comment by FiniteReality** [comment]
Looking awesome - would https://hub.docker.com/r/nercury/cmake-cpp/ work instead of a custom image? It appears to have the correct versions except it is missing TBB.

**Comment by Git-Jiro** [comment]
I tried the image you are suggesting right now. No, it does not work. At the moment your build only works with 32bit containers.

**Comment by FiniteReality** [comment]
Ah, ok, that's a shame. Is this ready to merge?

**Comment by Git-Jiro** [comment]
Yes, It's working perfectly fine with my fork.

**Comment by FiniteReality** [comment]
Awesome, thanks 👍

**Comment by Git-Jiro** [comment]
There is one thing you might want to adapt:
1. Create a Docker Hub account on https://hub.docker.com/
2. Create a repository with an automated build for "container/Dockerfile" on Docker Hub
3. Change gitjiro/sourcelua to your Docker image from Docker Hub instead of mine.

**Comment by FiniteReality** [comment]
Yeah, will do.

**Pull request merged**
